name: Build & Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v14

      - uses: cachix/cachix-action@v15
        with:
          name: mtul
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build & push to cachix
        run: |
          nix build .#cliproxyapi --print-out-paths | cachix push mtul
          nix build .#cpa-usage-keeper --print-out-paths | cachix push mtul
